export const products = [
  // ── Ugly Cute Monsters ───────────────────────────────────────────────────
  {
    id: 'ucm-teeth-001',
    name: 'Toothy Monster Plush',
    subtitle: '9" Funny Stuffed Animal',
    price: 22.99,
    originalPrice: 32.99,
    emoji: '🦷',
    tag: 'Best Seller',
    tagColor: 'bg-uc-green text-uc-dark',
    collection: 'monsters',
    image: 'https://s.alicdn.com/@sc04/kf/H5ad700445ab54a6f91dba20f1c4ed99cm.jpg',
    images: [
      'https://s.alicdn.com/@sc04/kf/H5ad700445ab54a6f91dba20f1c4ed99cm.jpg',
      'https://s.alicdn.com/@sc04/kf/H419e616864b048e8988609030ac7d8aad.jpg',
      'https://s.alicdn.com/@sc04/kf/H68aab92d76474b76ab182a05dacb81fcs.jpg',
    ],
    description: 'Big googly eyes, floppy ears, and a grin full of teeth. So wrong. So right.',
    longDescription: "Introducing the Ugly Cute Monster Plush — the stuffed animal that's so wrong, it's absolutely right. With its oversized googly eyes and hilariously protruding teeth, this 9-inch monster plushie is the ultimate gift for anyone who dares to be different.",
    features: ['9 inches of ugly cuteness', 'Ultra-soft premium plush', 'PP cotton fill', 'Safe for ages 3+', 'Hand wash cold'],
    specs: { Size: '9 inches (23 cm)', Material: 'Premium short plush, PP cotton', Eyes: 'Safe plastic googly eyes', 'Age Rating': '3+ years', Care: 'Hand wash cold, air dry' },
    slug: 'toothy-monster-plush',
    inStock: true,
  },
  {
    id: 'ucm-roach-001',
    name: 'Cockroach Bestie Plush',
    subtitle: '9.8" Cartoon Bug Stuffed Animal',
    price: 19.99,
    originalPrice: 28.99,
    emoji: '🪳',
    tag: 'Gag Gift Pick',
    tagColor: 'bg-uc-purple text-white',
    collection: 'monsters',
    image: 'https://s.alicdn.com/@sc04/kf/Hb3f56d94dc934a048f3e1da74f4a4d79e.jpg',
    images: [
      'https://s.alicdn.com/@sc04/kf/Hb3f56d94dc934a048f3e1da74f4a4d79e.jpg',
      'https://s.alicdn.com/@sc04/kf/H73c964adbe76436eb347e67638dce71cz.jpg',
      'https://s.alicdn.com/@sc04/kf/Ha63720a999e04d76a45bf4cb83fd6168q.jpg',
    ],
    description: 'Chubby, lovable, and misunderstood. Roachie just wants to be your best friend.',
    longDescription: "A chubby, huggable cartoon roach that's oddly impossible to resist. With its round body, tiny legs, and goofy expression, this plushie flips the script on everyone's least favorite insect.",
    features: ['9.8 inches of roach realness', 'Super soft & squishy', 'PP cotton fill', 'Sits upright on its own', 'Safe for ages 3+'],
    specs: { Size: '9.8 inches (25 cm)', Material: 'Short plush, PP cotton', Style: 'Cartoon cockroach', 'Age Rating': '3+ years', Care: 'Spot clean or hand wash' },
    slug: 'cockroach-bestie-plush',
    inStock: true,
  },
  {
    id: 'ucm-keychain-001',
    name: 'Monster Keychain',
    subtitle: 'Mini Plush Bag Charm',
    price: 14.99,
    originalPrice: 19.99,
    emoji: '🎃',
    tag: 'Impulse Buy',
    tagColor: 'bg-yellow-400 text-uc-dark',
    collection: 'monsters',
    image: 'https://s.alicdn.com/@sc04/kf/H0c7c02e09c3b44a9bce602a75c888f6a2.jpg',
    images: [
      'https://s.alicdn.com/@sc04/kf/H0c7c02e09c3b44a9bce602a75c888f6a2.jpg',
      'https://s.alicdn.com/@sc04/kf/A235137fd229a4a02a33200262e019f1cv.png_220x220.png',
      'https://s.alicdn.com/@sc04/kf/H1883023e84e04c87b68e70259368a8e6s.jpg',
    ],
    description: 'Clip one on your bag. Let the monster do the talking. Collect them all.',
    longDescription: "Clip this Ugly Cute Monster Plush Keychain onto your bag, keys, or backpack and let the world know you have excellent (terrible) taste. Each mini monster is uniquely goofy.",
    features: ['Pocket-sized ugly cuteness', 'Sturdy metal keyring', 'Lobster clasp attachment', 'Collectible series', 'Great for all ages 6+'],
    specs: { Size: '4 inches (10 cm)', Material: 'Short plush, PP cotton, metal ring', Attachment: 'Metal split ring + lobster clasp', 'Age Rating': '6+ years', Note: 'Design may vary' },
    slug: 'monster-keychain',
    inStock: true,
  },

  // ── Kawaii Girl Collection ───────────────────────────────────────────────
  {
    id: 'ucm-capy-001',
    name: 'Kawaii Capybara Plush',
    subtitle: '8" Cute Soft Stuffed Animal',
    price: 18.99,
    originalPrice: 26.99,
    emoji: '🦫',
    tag: 'Trending',
    tagColor: 'bg-pink-400 text-white',
    collection: 'kawaii',
    image: 'https://s.alicdn.com/@sc04/kf/Hce49e902a4d4407dad9353903acc4448a.jpg',
    images: [
      'https://s.alicdn.com/@sc04/kf/Hce49e902a4d4407dad9353903acc4448a.jpg',
      'https://s.alicdn.com/@sc04/kf/Ha81f4794e05f479f8daf2c928b9adba3U.jpg',
      'https://s.alicdn.com/@sc04/kf/H6272f3417f2e4dea978b521f7ac8778dK.jpg',
    ],
    description: "The internet's most beloved unbothered animal, now in ultra-soft plush form.",
    longDescription: "Meet the Kawaii Capybara Plush — inspired by the internet's most beloved unbothered animal, this ultra-soft 8-inch plushie is equal parts adorable and therapeutic. Premium PP cotton fill with velvety short plush exterior, perfect for squeezing during stressful moments.",
    features: ['8 inches of chill capybara energy', 'Ultra-soft velvety plush', 'Premium PP cotton fill', 'Aesthetic room decor piece', 'Safe for ages 3+'],
    specs: { Size: '8 inches (20 cm)', Material: 'Premium short plush, PP cotton', Style: 'Kawaii cartoon capybara', 'Age Rating': '3+ years', Care: 'Hand wash cold, air dry' },
    slug: 'kawaii-capybara-plush',
    inStock: true,
  },
  {
    id: 'ucm-bunny-001',
    name: 'Soft Kawaii Bunny Plush',
    subtitle: '12" Jellycat-Style Floppy Rabbit',
    price: 32.99,
    originalPrice: 44.99,
    emoji: '🐰',
    tag: 'Gift Favourite',
    tagColor: 'bg-purple-400 text-white',
    collection: 'kawaii',
    image: 'https://s.alicdn.com/@sc04/kf/Hf22ad74d65b642d0bef16afdd995456b6.jpg',
    images: [
      'https://s.alicdn.com/@sc04/kf/Hf22ad74d65b642d0bef16afdd995456b6.jpg',
      'https://s.alicdn.com/@sc04/kf/Hbb932962176d424bb69b608486888c11n.png_220x220.png',
      'https://s.alicdn.com/@sc04/kf/H8734037f3a2d4487a296c858eb4a5ecdq.jpg',
    ],
    description: 'Cloud-level softness. Floppy ears. Dreamy expression. Your new emotional support bestie.',
    longDescription: "Meet your new favorite cuddle companion — a Jellycat-inspired Kawaii Bunny Plush so impossibly soft, you'll wonder how you ever lived without it. With its floppy ears, dreamy expression, and cloud-like texture, this bunny is pure comfort in plush form.",
    features: ['12 inches of pure softness', 'Cloud-level plush texture', 'Long floppy ears for fidgeting', 'Premium PP cotton fill', 'Safe for ages 3+'],
    specs: { Size: '12 inches (31 cm)', Material: 'Ultra-soft plush, PP cotton fill', Style: 'Floppy-ear kawaii bunny', 'Age Rating': '3+ years', Care: 'Hand wash cold, air dry flat' },
    slug: 'soft-kawaii-bunny-plush',
    inStock: true,
  },
  {
    id: 'ucm-boba-001',
    name: 'Boba Milk Tea Bear Plush',
    subtitle: '10" Kawaii Bubble Tea Stuffed Animal',
    price: 19.99,
    originalPrice: 27.99,
    emoji: '🧋',
    tag: 'TikTok Fave',
    tagColor: 'bg-amber-400 text-uc-dark',
    collection: 'kawaii',
    image: 'https://s.alicdn.com/@sc04/kf/H0d066b29be32410f96bf70aa4576ed6eG.jpg',
    images: [
      'https://s.alicdn.com/@sc04/kf/H0d066b29be32410f96bf70aa4576ed6eG.jpg',
      'https://s.alicdn.com/@sc04/kf/Hbd3a7cba43a344788871286579b35743J.jpg',
      'https://s.alicdn.com/@sc04/kf/H186633eab02346d0b361f3f94763df1aA.jpg',
    ],
    description: '100% huggable. 0% calories. The cutest drink you will ever hug.',
    longDescription: "Introducing the Boba Milk Tea Bear Plush — a kawaii stuffed animal shaped like everyone's favorite drink. Chubby, squishy, and irresistibly cute, this plushie is the perfect blend of food obsession and plush comfort.",
    features: ['10 inches of boba goodness', 'Super squishy PP cotton fill', 'Unique bubble tea cup design', 'TikTok-ready aesthetic', 'Safe for ages 3+'],
    specs: { Size: '10 inches (25 cm)', Material: 'Short plush, PP cotton', Style: 'Kawaii bubble tea cup with animal', 'Age Rating': '3+ years', Care: 'Spot clean or hand wash, air dry' },
    slug: 'boba-milk-tea-bear-plush',
    inStock: true,
  },
]

export const collections = {
  monsters: {
    id: 'monsters',
    name: 'Ugly Cute Monsters',
    emoji: '👾',
    description: 'Creatures so hideous, so lovable — you won\'t be able to stop at just one.',
    color: 'bg-uc-dark',
    textColor: 'text-white',
  },
  kawaii: {
    id: 'kawaii',
    name: 'Kawaii Girl Collection',
    emoji: '🌸',
    description: 'Soft, squishy, and impossibly cute — aesthetic plushies for girls who love to feel good.',
    color: 'bg-pink-50',
    textColor: 'text-pink-800',
  },
}

export function getProductBySlug(slug) {
  return products.find(p => p.slug === slug)
}

export function getProductsByCollection(collectionId) {
  return products.filter(p => p.collection === collectionId)
}
