export const products = [
  {
    id: 'ucm-teeth-001',
    name: 'Toothy Monster Plush',
    subtitle: '9" Funny Stuffed Animal',
    price: 22.99,
    originalPrice: 32.99,
    emoji: '🦷',
    tag: 'Best Seller',
    tagColor: 'bg-uc-green text-uc-dark',
    image: 'https://s.alicdn.com/@sc04/kf/H5ad700445ab54a6f91dba20f1c4ed99cm.jpg',
    images: [
      'https://s.alicdn.com/@sc04/kf/H5ad700445ab54a6f91dba20f1c4ed99cm.jpg',
      'https://s.alicdn.com/@sc04/kf/H419e616864b048e8988609030ac7d8aad.jpg',
      'https://s.alicdn.com/@sc04/kf/H68aab92d76474b76ab182a05dacb81fcs.jpg',
    ],
    description: 'Big googly eyes, floppy ears, and a grin full of teeth. So wrong. So right.',
    longDescription: 'Introducing the Ugly Cute Monster Plush — the stuffed animal that\'s so wrong, it\'s absolutely right. With its oversized googly eyes and hilariously protruding teeth, this 9-inch monster plushie is the ultimate gift for anyone who dares to be different.',
    features: ['9 inches of ugly cuteness', 'Ultra-soft premium plush', 'PP cotton fill', 'Safe for ages 3+', 'Hand wash cold'],
    specs: { Size: '9 inches (23 cm)', Material: 'Premium short plush, PP cotton', Eyes: 'Safe plastic googly eyes', 'Age Rating': '3+ years', Care: 'Hand wash cold, air dry' },
    slug: 'toothy-monster-plush',
    inStock: true,
  },
  {
    id: 'ucm-roach-001',
    name: 'Cockroach Bestie Plush',
    subtitle: '9.8" Cartoon Bug Stuffed Animal',
    price: 19.99,
    originalPrice: 28.99,
    emoji: '🪳',
    tag: 'Gag Gift Pick',
    tagColor: 'bg-uc-purple text-white',
    image: 'https://s.alicdn.com/@sc04/kf/Hb3f56d94dc934a048f3e1da74f4a4d79e.jpg',
    images: [
      'https://s.alicdn.com/@sc04/kf/Hb3f56d94dc934a048f3e1da74f4a4d79e.jpg',
      'https://s.alicdn.com/@sc04/kf/H73c964adbe76436eb347e67638dce71cz.jpg',
      'https://s.alicdn.com/@sc04/kf/Ha63720a999e04d76a45bf4cb83fd6168q.jpg',
    ],
    description: 'Chubby, lovable, and misunderstood. Roachie just wants to be your best friend.',
    longDescription: 'A chubby, huggable cartoon roach that\'s oddly impossible to resist. With its round body, tiny legs, and goofy expression, this plushie flips the script on everyone\'s least favorite insect.',
    features: ['9.8 inches of roach realness', 'Super soft & squishy', 'PP cotton fill', 'Sits upright on its own', 'Safe for ages 3+'],
    specs: { Size: '9.8 inches (25 cm)', Material: 'Short plush, PP cotton', Style: 'Cartoon cockroach', 'Age Rating': '3+ years', Care: 'Spot clean or hand wash' },
    slug: 'cockroach-bestie-plush',
    inStock: true,
  },
  {
    id: 'ucm-keychain-001',
    name: 'Monster Keychain',
    subtitle: 'Mini Plush Bag Charm',
    price: 14.99,
    originalPrice: 19.99,
    emoji: '🎃',
    tag: 'Impulse Buy',
    tagColor: 'bg-yellow-400 text-uc-dark',
    image: 'https://s.alicdn.com/@sc04/kf/H0c7c02e09c3b44a9bce602a75c888f6a2.jpg',
    images: [
      'https://s.alicdn.com/@sc04/kf/H0c7c02e09c3b44a9bce602a75c888f6a2.jpg',
      'https://s.alicdn.com/@sc04/kf/A235137fd229a4a02a33200262e019f1cv.png_220x220.png',
      'https://s.alicdn.com/@sc04/kf/H1883023e84e04c87b68e70259368a8e6s.jpg',
    ],
    description: 'Clip one on your bag. Let the monster do the talking. Collect them all.',
    longDescription: 'Clip this Ugly Cute Monster Plush Keychain onto your bag, keys, or backpack and let the world know you have excellent (terrible) taste. Each mini monster is uniquely goofy.',
    features: ['Pocket-sized ugly cuteness', 'Sturdy metal keyring', 'Lobster clasp attachment', 'Collectible series', 'Great for all ages 6+'],
    specs: { Size: '4 inches (10 cm)', Material: 'Short plush, PP cotton, metal ring', Attachment: 'Metal split ring + lobster clasp', 'Age Rating': '6+ years', Note: 'Design may vary' },
    slug: 'monster-keychain',
    inStock: true,
  },
]

export function getProductBySlug(slug) {
  return products.find(p => p.slug === slug)
}
